### ISSUE TITLE
Manually add bots in channels

### ISSUE THREAD

**Issue by rcombs** [lformella/xdcc-grabscher#19]
Not all bots announce themselves; there should be an option to specify those which don't by nick.

**Comment by lformella** [comment]
If you add a bot manually you are still not able to download packages, because if the bot does not announce himself, there will be no packages. You can bypass this logic by entering a valid xdcc link via the settings popup. There you can enter a server, channel, bot and packet. If any of them already exists, it will be ignored. The packet is automatically enabled and requested.

XDCC links you can find at http://xg.bitpir.at/ (is based on xg and only lists announced bots, too) or http://www.xweasel.org/ (seems broken atm)

**Comment by rcombs** [comment]
If a bot doesn't annoilunce itself, the XDCC SEARCH and XDCC LIST commands could be used to retrieve the packlist.
—

**Comment by lformella** [comment]
XG 3.0.0.0 (https://github.com/lformella/xdcc-grabscher/releases/tag/v3.0.0.0) supports XDCC LIST commands

take a look in the README
