### ISSUE TITLE
XG does not shutdown when using linked folder

### ISSUE THREAD

**Issue by Strubbl** [lformella/xdcc-grabscher#41]
My XG configuration directory ~/.config/XG is a link to another directory. Maybe this is the reason XG does not shutdown when I use the stop.sh script? 
To shutdown XG I have to use ctrl+c.

**Comment by lformella** [comment]
I dropped the possibility to stop XG via shutdown file (used by stop.sh), because I enabled ctrl+c (inkl. other system hooks) and the button in the webfrontend (#40). The file was an ugly workaround to stop XG gracefully, because I did not know how to catch terminal signals at this time. Do you still need the shutdown file / stop.sh?

**Comment by Strubbl** [comment]
No, thanks. Not needed. I just thought using ctrl+c might destroy the database. But when xg uses signal handling i am fine. I like that solution and the possibilty with the shutdown button in the gui
