### ISSUE TITLE
Max bot Connections

### ISSUE THREAD

**Issue by Jaglag** [lformella/xdcc-grabscher#67]
would be nice to set max bot connections.
for example set to 3 and the other bots set to a seperate waiting queue till 1 is finished.

**Comment by lformella** [comment]
Unfortunately you cant control the beginning of a download. If you want a packet you send a request and the bot decides if and when you can download the packet. If you receive an download offer, you have to take it. If you dont, you have to request the packet and wait again.

What should happen if you allow 2 connections but select 4 packets? Should XG request all of them? What if all bots have a large queue which forces you to wait some hours? Should XG ignore the rare download offer and wait again because all slots are in use?
Or should XG just request 2 packets at once? What if the bot is not reacting? What if the bot has a large queue and blocks the next packet?

**Comment by Jaglag** [comment]
i using a script atm dccassist this handle the request fine.
i set it to 2 dcc at same time if the bot have a large queue you are right i have to wait till the first two packets dl and then wait till the queue is finished but i select up to 20-30 packets a day when all these dl running on same time my mirc your client and my computer starts to lagging cause of all the packets dl at same time.
i think the best way to handle this is via your client if i set it to 2 or 4 connections he should internal queue all other items cause no connection can handle 20-30 packets at same time not even with my ssd.
