### ISSUE TITLE
Database structure help?

### ISSUE THREAD

**Issue by alliao** [lformella/xdcc-grabscher#8]
Hi Lars, Love this project! I have setup on my computer, but no idea how to prepare the database.
Is there something where I can setup the mysql database? so the server can talk to it?

Thanks! I have vs2012 installed, and compiled on windows7 64bits

**Comment by alliao** [comment]
I found your install.sql file... To those that are as newbie as me under windows

type "mysql -u login -p password xg < install.sql" will import it.

It's working wonderfully now. Thank you very much!

**Comment by lformella** [comment]
Why are you using the mysql database? Normally you dont need to use the database backend, because XG is working fine just using the normal file structrure. The database backend is just there because i use it at xg.bitpir.at to build a live search enigne. Because of this it lacks some features like saving the informations which files you are downloading.
